/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fxj_pcmtranscodemp3demo01_LameUtils */

#ifndef _Included_com_fxj_pcmtranscodemp3demo01_LameUtils
#define _Included_com_fxj_pcmtranscodemp3demo01_LameUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fxj_pcmtranscodemp3demo01_LameUtils
 * Method:    init
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_fxj_pcmtranscodemp3demo01_LameUtils_init
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_fxj_pcmtranscodemp3demo01_LameUtils
 * Method:    pcmToMp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fxj_pcmtranscodemp3demo01_LameUtils_pcmToMp3
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fxj_pcmtranscodemp3demo01_LameUtils
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fxj_pcmtranscodemp3demo01_LameUtils_destory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
